import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.className} lang="en">
      <body className="flex flex-col w-full ">
        <div className="bg-blue-100 w-full ">
          <Header />
        </div>
        <main className="grow w-full max-w-screen-2xl mx-auto">{children}</main>
        <div className="w-full max-w-screen-2xl mx-auto">
          <Footer />
        </div>
      </body>
    </html>
  );
}
